services:
  wc-grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
          - "3000:3000"
      environment:
          - GF_SECURITY_ADMIN_USER=admin
          - GF_SECURITY_ADMIN_PASSWORD=admin
          - GF_SERVER_ROOT_URL=http://localhost:3000/grafana
          - GF_SERVER_SERVE_FROM_SUB_PATH=true
          - GF_AUTH_INFLUXDB_ENABLED=true
          # SMTP Configuration
          # - GF_SMTP_ENABLED=true
          # - GF_SMTP_HOST=dosiujad
          # - GF_SMTP_USER=asdji
          # - GF_SMTP_PASSWORD=aowid
          # - GF_SMTP_FROM_ADDRESS=oaiwd
          # - GF_SMTP_FROM_NAME=Grafana Alerts
          # - GF_SMTP_STARTTLS_POLICY=MandatoryStartTLS
      volumes:
          - ./grafana-data:/var/lib/grafana
      restart: always
      user: "1000"


volumes:
  grafana-data:
