services:
  wc-grafana:
      image: grafana/grafana:latest
      container_name: grafana
      env_file:
          - .env
      ports:
          - "80:3000"
      environment:
          - GF_SECURITY_ADMIN_USER=admin
          - GF_SECURITY_ADMIN_PASSWORD=admin
          - GF_SERVER_ROOT_URL=http://localhost
          - GF_SERVER_SERVE_FROM_SUB_PATH=true
          - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
          - AWS_REGION=us-east-1
      volumes:
          # Persiste dados e configurações internas do Grafana
          - grafana-storage:/var/lib/grafana
      restart: always
      user: "1000"

volumes:
  # Volume nomeado para persistência entre reinícios/recriações
  grafana-storage:
