services:
  wc-grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
          - "80:3000"
      environment:
          - GF_SECURITY_ADMIN_USER=admin
          - GF_SECURITY_ADMIN_PASSWORD=admin
          - GF_SERVER_ROOT_URL=http://localhost
          - GF_SERVER_SERVE_FROM_SUB_PATH=true
          - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          - AWS_REGION=us-east-1
      restart: always
      user: "1000"
